Add Rego doc
chainguard-dev/edu pull request #251
Opened 2023-01-06 01:39 UTC by ltagliaferri

Adding rego policies doc

Signed-off-by: ltagliaferri

2023-01-09 23:19 UTC, SharpRake requested changes
Some minor tweaks, plus one paragraph where I had a slightly different interpretation of Adam's blog post. LMK if you have any questions on anything!

2023-01-10 21:07 UTC, ltagliaferri commented on content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-rego-policies.md
> +Within the `isCompliant` braces, multiple conditions may exist if they are added together with the `AND` keyword Multiple evaluations within different sets of braces may also exist in the policy, the
May be worth calling out that Rego has this functionality that is not in the box with Enforce

2023-01-13 00:54 UTC, ltagliaferri commented on content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/annotation-based-caching.md
> +In Chainguard's own load testing annotation-based caching, with a cache hit we see P99 verification latency of under 2s, and no egress was made to container registry. Without caching, latency would b
I added a parenthetical explanation of P99, see https://stackoverflow.com/questions/12808934/what-is-p99-latency

2023-01-13 00:58 UTC, ltagliaferri commented on content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-kubernetes-faq.md
> +> _This document relates to Chainguard Enforce. In order to follow along, you will need access to Chainguard Enforce. You can request access through selecting **Chainguard Enforce for Kubernetes** on
I guess we should do it

2023-01-13 17:09 UTC, SharpRake approved these changes
Just a couple very minor suggestions. Otherwise this looks great!

2023-01-13 17:22 UTC, merged