Vex
chainguard-dev/edu pull request #323
Opened 2023-01-31 20:41 UTC by sheesh

## Type of change

### What should this PR do?

### Why are we making this change?

### What are the acceptance criteria? 

### How should this PR be tested?

2023-01-31 21:43 UTC, ltagliaferri requested changes
I think this should be in the SBOM directory. I made some comments, I think I don't have the full context so I would use your best judgement on some of my suggestions

2023-01-31 21:43 UTC, ltagliaferri commented on config/_default/menus/menus.en.toml
> +  name = "VEX"
Let's put VEX under SBOMs and take this out

2023-01-31 21:43 UTC, ltagliaferri commented on content/open-source/vex/what-is-openvex.md
> +With OpenVex, stakeholders from across the software supply chain can collaborate on identifying and remediating exploitable vulnerabilities and use automation to enable more precise and efficient met
```suggestion
With OpenVex, stakeholders from across the software supply chain can collaborate on identifying and remediating exploitable vulnerabilities and use automation to enable more precise and efficient methods of security management. In this guide, you will learn more about the emerging supply chain security standards that OpenVex supports, and how OpenVex tooling can help you leverage them in your security management processes. 
```

"security management" sounds like an adjective to me, maybe can also be "approach" or "practice" if you want to be academic about it

2023-01-31 21:43 UTC, ltagliaferri commented on content/open-source/vex/what-is-openvex.md
> +Incorporating a [software bill of materials (SBOM)](https://edu.chainguard.dev/open-source/sbom/what-is-an-sbom/) is a powerful way of enabling visibility into your codebase so that vulnerabilities a
"Powerful" feels a little strong. I would remove "easily" here, I think "identified in a timely manner" is enough without overdoing it

Would a software end user think about an SBOM? It sounds like a stretch. If you mean something else (developers, operators, etc., I would clarify)

```suggestion
Incorporating a [software bill of materials (SBOM)](https://edu.chainguard.dev/open-source/sbom/what-is-an-sbom/) is an efficient way of enabling visibility into your codebase so that vulnerabilities are identified in a timely manner. When vulnerabilities are made known through security advisories, software users can refer to their SBOM(s) to see if they have dependencies associated with the specified vulnerability. In this way, SBOMs represent a significant step forward in security management, enabling the quick identification of vulnerabilities, which can otherwise can a significant amount of labor. For example, [one federal agency reportedly spent 33,000 hours responding to the Log4j vulnerability](https://federalnewsnetwork.com/commentary/2023/01/application-security-a-pillar-of-zero-trust/) at the expense of other priorities. 

Though the SBOM's affordance of heightened visibility greatly improves an organization's security posture, it can be accompanied by an overproduction of false positives or vulnerabilities that are associated with an organization's codebase but have been determined to not be exploitable in specific circumstances. This increase in false positives can impede upon an SBOM's security utility as organizations are tasked with investigating the broadened list of vulnerabilities to see which ones pose genuine threats to their codebase. In this case, organizations may once again struggle to efficiently identify and respond to vulnerabilities before it is too late.  
```

2023-01-31 21:43 UTC, ltagliaferri commented on content/open-source/vex/what-is-openvex.md
> +To address this problem, SBOM working groups came up with the idea of the Vulnerability Exploitability eXchange (VEX), a system designed to help users eliminate vulnerability “noise” and focus on vul
I think "software vulnerability" is ok here to remove some prepositions. I think "software product" would be better as "software artifact" if you want to keep the original structure

```suggestion
To address this problem, SBOM working groups came up with the idea of the Vulnerability Exploitability eXchange (VEX), a system designed to help users eliminate vulnerability “noise” and focus on vulnerabilities that present a genuine risk to their organization. VEX is a mechanism that enables software suppliers and third party stakeholders (such as security researchers) to publish machine-readable security advisories on the status of Common Vulnerabilities and Exposures (CVEs). When publishing a VEX document for a known software vulnerability, the author assigns the product a status drawn from the following list: 
```

2023-01-31 21:43 UTC, ltagliaferri commented on content/open-source/vex/what-is-openvex.md
> +Once published, users of the software product (such as operators or developers) can use these VEX documents to determine whether they are impacted by a vulnerability and what steps they might need to
If "software product" is common in the language for SBOMs then you should stet

Here, maybe I would change "the software product" to "a given software"

2023-01-31 21:43 UTC, ltagliaferri commented on content/open-source/vex/what-is-openvex.md
> +Once published, users of the software product (such as operators or developers) can use these VEX documents to determine whether they are impacted by a vulnerability and what steps they might need to
Also, this explanation of "users" (operators or developers) should go up higher where I complained about the "user" word 😂

2023-01-31 21:43 UTC, ltagliaferri commented on content/open-source/vex/what-is-openvex.md
> +VEX has value for stakeholders across the supply chain, enabling collaboration across suppliers, operators, and end users that can save the community significant amounts of time investigating and mit
```suggestion
VEX has value for stakeholders across the supply chain, enabling collaboration across suppliers, operators, and end users that can save the community significant amounts of time investigating and mitigating vulnerabilities. Software suppliers can use VEX to let their users know when they’ve already investigated a vulnerability and whether that vulnerability affects the product or if further action needs to be taken by the user. And in the case that  end users investigate potential vulnerabilities without a security advisory, they can encode their findings in a VEX document to share with the supplier or track for future or ongoing investigations.
```

2023-01-31 21:43 UTC, ltagliaferri commented on content/open-source/vex/what-is-openvex.md
> +This command will result in output that show vulnerabilities from the scanner that not resolved by the VEX document.
```suggestion
This command will result in output that shows vulnerabilities from the scanner that are not resolved by the VEX document. 
```

2023-01-31 21:43 UTC, ltagliaferri commented on content/open-source/vex/what-is-openvex.md
> +* [Reflections on Trusting VEX (or when humans can improve SBOMs)](https://www.chainguard.dev/unchained/)reflections-on-trusting-vex-or-when-humans-can-improve-sboms_
```suggestion
* [Reflections on Trusting VEX (or when humans can improve SBOMs)](https://www.chainguard.dev/unchained/reflections-on-trusting-vex-or-when-humans-can-improve-sboms)
```

2023-01-31 21:43 UTC, ltagliaferri commented on content/open-source/vex/what-is-openvex.md
> +https://www.chainguard.dev/unchained/understanding-the-promise-of-vex)
```suggestion
```

2023-01-31 22:46 UTC, ltagliaferri commented on content/open-source/vex/what-is-openvex.md
> +Or, to filter out “Vex’ed out” vulnerabilities from security scanner results, you can use the `filter` command.  In this example, `scan_results.sarif.json` is the file with the scanner results and `v
what is "vex'ed out" btw?

```suggestion
Or, to filter out “VEX’ed out” vulnerabilities from security scanner results, you can use the `filter` command.  In this example, `scan_results.sarif.json` is the file with the scanner results and `vex_data.csaf` contains the VEX information.  
```

2023-01-31 23:19 UTC, sheesh commented on content/open-source/vex/what-is-openvex.md
> +Once published, users of the software product (such as operators or developers) can use these VEX documents to determine whether they are impacted by a vulnerability and what steps they might need to
Software product is used in vex documentation, but I agree it's confusing here. Adjusted the wording. 

Also adjusting use of "users" in this guide.

2023-02-01 04:12 UTC, ltagliaferri approved these changes

2023-02-01 04:12 UTC, merged